worker_processes	1;

events {
	worker_connections  10240;
}

http {
	include       mime.types;
	default_type  application/octet-stream;

	#TCP优化
	sendfile        on;
	tcp_nopush on;
	keepalive_timeout 600;
	tcp_nodelay on;

	#GZIP优化
	gzip  on;
	gzip_buffers 16 8k;
	gzip_comp_level 6;
	gzip_http_version 1.0;
	gzip_min_length 1000;
	gzip_proxied any;
	gzip_vary on;
	gzip_types
		text/xml application/xml application/atom+xml application/rss+xml application/xhtml+xml image/svg+xml
		text/javascript application/javascript application/x-javascript
		text/x-json application/json application/x-web-app-manifest+json
		text/css text/plain text/x-component
		font/opentype application/x-font-ttf application/vnd.ms-fontobject
		image/x-icon;
	gzip_disable "MSIE [1-6]\.(?!.*SV1)";

	#统一使用utf-8字符集
	charset	utf-8;

	#连接参数优化
	client_header_buffer_size 32k;
	large_client_header_buffers 4 32k;
	client_max_body_size 2048m;
	client_body_buffer_size 10m;

	include conf.d/*.conf;
}

stream{

}
