# 本地项目
location ^~/basicData/ {
    proxy_pass http://localhost:3300/basicData/;
}

location ^~/outPatientDoctor/ {
    proxy_pass http://localhost:8081/outPatientDoctor/;
}

location ^~/residentDoctor/ {
    proxy_pass http://localhost:5173/residentDoctor/;
}

location ^~/middle/ {
#    proxy_pass http://localhost:9000/middle/;
#     proxy_pass http://localhost:4173/middle/;
     proxy_pass http://192.168.209.103:9099/middle/;
}

location ^~/test/ {
    proxy_pass http://localhost:3301/test/;
}

location ^~/skywalking/ {
    proxy_pass http://localhost:3006/skywalking/;
}