# 本地项目

# 基础数据
location ^~/basicData/ {
    proxy_pass http://localhost:3300/basicData/;
}

# 门诊医生
location ^~/outPatientDoctor/ {
    proxy_pass http://localhost:8081/outPatientDoctor/;
}

# 住院医生
location ^~/residentDoctor/ {
    proxy_pass http://localhost:3300/residentDoctor/;
}

# 住院护士
location ^~/residentNurse/ {
    proxy_pass http://localhost:5173/residentNurse/;
}

location ^~/outPatientNurse/ {
    proxy_pass http://localhost:3008/outPatientNurse/;
}

location ^~/test/ {
    proxy_pass http://localhost:3301/test/;
}

location ^~/skywalking/ {
    proxy_pass http://localhost:3006/skywalking/;
}
