# 本地项目
location ^~/basicData/ {
    try_files $uri $uri/ /index.html;
    proxy_pass http://localhost:3300/basicData/;
}

location ^~/outPatientDoctor/ {
    try_files $uri $uri/ /index.html;
    proxy_pass http://localhost:8081/outPatientDoctor/;
}

location ^~/residentDoctor/ {
    try_files $uri $uri/ /index.html;
    proxy_pass http://localhost:3300/residentDoctor/;
}

location ^~/test/ {
    try_files $uri $uri/ /index.html;
    proxy_pass http://localhost:3301/test/;
}

location ^~/skywalking/ {
    try_files $uri $uri/ /index.html;
    proxy_pass http://localhost:3006/skywalking/;
}