# 本地静态资源

# # 全局静态资源不缓存配置
# location ~* \.(js|css|html|htm|json|xml|txt|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$ {
# 	# 完全禁用缓存
# 	add_header Cache-Control "no-cache, no-store, must-revalidate";
# 	add_header Pragma "no-cache";
# 	add_header Expires "0";
#
# 	# 禁用ETag
# 	etag off;
# }

location ^~/vueComponents/ {
	# 打包以后的项目路径
	alias html/vitepress/;
	
	# 解决404问题
	try_files $uri $uri/ /vitepress/index.html;
}