# 本地静态资源
location ^~/vueComponents/ {
	add_header Cache-Control no-cache;
	add_header Cache-Control private;
	expires -1s;
	#打包以后的项目路径
	alias html/vitepress/;
	#解决404问题
	try_files $uri $uri/ /vitepress/index.html;
}